modLoader="javafml"
loaderVersion="[41,)"
license="CC0"
[[mods]]
modId="contextually"
version="${file.jarVersion}"
displayName="Contextually"
logoFile=""
credits=""
authors="Dhyces"
description='''
Welcome to a new knowledgable world
'''
[[dependencies.contextually]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.contextually]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
